name: Deploy

on:
  push:
    branches:[ main ]

jobs:
  Deploy:
    name: Deploy to my server
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env: 
          PRIVATE_KEY: ${{ secrets.SHH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IP_ADDRESS }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY }}

        run: | 
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

          cd /home/${USER_NAME}/${PROJECT_DIRECTORY}/ && git checkout dev &&
          git fetch --all && git reset --hard origin/main && 
          git pull origin main && sudo npm i && sudo npm run dev 




