name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    env: 
      PRIVATE_KEY: ${{ secrets.SHH_PRIVATE_KEY }}
      HOSTNAME: ${{ secrets.IP_ADDRESS }}
      USER_NAME: ${{ secrets.USER_NAME }}
      PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY }}
      PASSWORD: ${{ secrets.PASSWORD }}


    name: Deploy to my server
    runs-on: ubuntu-latest

    steps: 
      - name: connect to server using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: | 
            cd /CI_CD_test  
            git reset --hard 
            git pull origin main 
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo rm -rf nuxt_archive.tar.gz

      - name: checkout code
        uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@main
        with:
          node-version: "latest"
          
      - run: pwd
      - run: npm audit fix
      - run: npm i 
      - run: npm run build --if-present
      - run: mkdir -p out
      - run: tar -czvf out/nuxt_archive.tar.gz .output
      
      - name: run system
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: | 
            cd /CI_CD_test  
            - name: connect to server using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: | 
            cd /CI_CD_test  
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /CI_CD_test  
            sudo rm -rf nuxt_archive.tar.gz
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 restart all


        



